### ISSUE TITLE
Chess could not be compiled

### ISSUE THREAD

**Issue by LeandroFavero** [buta/Chess#2]
Hello,

I downloaded the source code and tried to open it using Unreal 5.4.4. However, I received a message indicating that the version was different, and a rebuild was required. I attempted the rebuild but it failed. I then generated the project in Visual Studio, performed a clean and rebuild, but encountered the following errors during compilation.

Am I missing something?

P.S.: The compiled version worked perfectly, including with Stockfish 17 - 2024-09-06.
P.S. 2: I also tried on macOS but couldn't get it to work there either. However, I still need to investigate further, as it might be an incompatibility with Xcode.

![image](https://github.com/user-attachments/assets/e4ca6a51-39fc-4585-ac7f-af0456fe37cc)

**Comment by MiFavero** [comment]
SOLVED: The release is on version 4, which is causing the error. 
You need to download the latest version from the main branch for it to work on 5.4.4.

**Comment by MiFavero** [comment]
SOLVED: The release is on version 4, which is causing the error.
You need to download the latest version from the main branch for it to work on 5.4.4.

**Comment by LeandroFavero** [comment]
Worked! Thanks a lot!
